// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface Event {
  /**
   * Date and time
   */
  datetime?: string;

  /**
   * Date and time end
   */
  datetimeEnd?: string;

  /**
   * Form description
   */
  description?: string;

  /**
   * Location
   */
  location?: "Мега Лекторий" | "Гипер Лекторий" | "Башня";

  /**
   * URL
   */
  url?: string;
}
