// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface Location {
  /**
   * Maximum games in block
   */
  maxGames: number;

  /**
   * Game location description
   */
  description?: string;
}
